CONFIG_ZMK_NFC_PINS_AS_GPIOS=y
# Bật tính năng ngủ sâu để tiết kiệm pin
CONFIG_ZMK_SLEEP=y
# Thời gian chờ để ngủ (900.000 ms = 15 phút)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Tăng cường độ tín hiệu Bluetooth (nếu phím để xa máy tính)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_KEYBOARD_NAME="Batoid 40"
CONFIG_ZMK_SLEEP=y
# Sau 15 phút không gõ sẽ tự đi ngủ sâu
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
